---

- name: Editors
  hosts: all
  tags: editors
  tasks:
  - name: Install Atom
    homebrew_cask:
      name: atom

  - name: Install Visual Studio Code
    homebrew_cask:
      name: visual-studio-code
